theme {
    style = Breeze
    icon_theme = Breeze
    color_scheme = $HOME/.config/qt6ct/colors/noctalia.conf
    font_fixed = Iosevka
    font_fixed_size = 12
    font = Figtree
    font_size = 12
}
